/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ReadingTimeStatPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/types.ts
var TIME_RANGE_OPTIONS = [
  { value: "all", label: "All Time" },
  { value: "today", label: "Today" },
  { value: "week", label: "Last 7 Days" },
  { value: "month", label: "Last 30 Days" },
  { value: "quarter", label: "Last 90 Days" },
  { value: "year", label: "Last Year" }
];
var DEFAULT_SETTINGS = {
  readingTimeWeight: 1,
  readingCountWeight: 5,
  recencyDecayFactor: 0.05,
  minSessionTime: 5,
  trackingInterval: 1e3,
  popularNotesLimit: 20,
  excludedFolders: [],
  excludedPatterns: []
};
var DEFAULT_STATS_DATA = {
  notes: {},
  trackingStartedAt: (/* @__PURE__ */ new Date()).toISOString(),
  version: 1
};

// src/stats.ts
var StatsManager = class {
  constructor(data, settings) {
    this.data = data != null ? data : { ...DEFAULT_STATS_DATA };
    this.settings = settings;
  }
  /**
   * Get current stats data
   */
  getData() {
    return this.data;
  }
  /**
   * Record a reading session for a note
   */
  recordReading(path, durationSeconds, wasEdited = false) {
    if (durationSeconds < this.settings.minSessionTime) {
      return;
    }
    const existing = this.data.notes[path];
    if (existing) {
      existing.totalReadingTime += durationSeconds;
      existing.readingCount += 1;
      existing.lastReadAt = (/* @__PURE__ */ new Date()).toISOString();
      if (wasEdited) {
        existing.hasEdited = true;
      }
    } else {
      const now = (/* @__PURE__ */ new Date()).toISOString();
      this.data.notes[path] = {
        totalReadingTime: durationSeconds,
        readingCount: 1,
        firstReadAt: now,
        lastReadAt: now,
        hasEdited: wasEdited
      };
    }
  }
  /**
   * Get stats for a specific note
   */
  getNoteStats(path) {
    return this.data.notes[path];
  }
  /**
   * Get all notes with stats
   */
  getAllNotes() {
    return this.data.notes;
  }
  /**
   * Delete stats for a note (when note is deleted)
   */
  deleteNote(path) {
    if (this.data.notes[path]) {
      delete this.data.notes[path];
      return true;
    }
    return false;
  }
  /**
   * Migrate stats from one path to another (when note is renamed/moved)
   * If the new path already has stats, the old data is discarded to avoid
   * conflicts.
   */
  migrateNote(oldPath, newPath) {
    if (oldPath === newPath) {
      return false;
    }
    const stats = this.data.notes[oldPath];
    if (!stats) {
      return false;
    }
    if (!this.data.notes[newPath]) {
      this.data.notes[newPath] = stats;
    }
    delete this.data.notes[oldPath];
    return true;
  }
  /**
   * Remove stats entries whose paths are not in the provided set of
   * existing paths. Returns the number of entries removed.
   */
  removeOrphans(existingPaths) {
    let removed = 0;
    for (const path of Object.keys(this.data.notes)) {
      if (!existingPaths.has(path)) {
        delete this.data.notes[path];
        removed++;
      }
    }
    return removed;
  }
  /**
   * Clear all statistics
   */
  clearAll() {
    this.data = {
      ...DEFAULT_STATS_DATA,
      trackingStartedAt: (/* @__PURE__ */ new Date()).toISOString()
    };
  }
  /**
   * Get total statistics summary
   */
  getSummary() {
    let totalTime = 0;
    let totalSessions = 0;
    for (const stats of Object.values(this.data.notes)) {
      totalTime += stats.totalReadingTime;
      totalSessions += stats.readingCount;
    }
    return {
      totalNotes: Object.keys(this.data.notes).length,
      totalTimeSeconds: totalTime,
      totalSessions,
      trackingStartedAt: this.data.trackingStartedAt
    };
  }
};

// src/exclusions.ts
function matchesPattern(filePath, pattern) {
  const regexPattern = pattern.replace(/\*/g, ".*").replace(/\?/g, ".").replace(/\./g, "\\.");
  const regex = new RegExp(`^${regexPattern}$`, "i");
  return regex.test(filePath);
}
function shouldExclude(filePath, settings) {
  const normalizedPath = filePath.startsWith("/") ? filePath.slice(1) : filePath;
  for (const folder of settings.excludedFolders) {
    const normalizedFolder = folder.startsWith("/") ? folder.slice(1) : folder;
    const folderPath = normalizedFolder.endsWith("/") ? normalizedFolder : normalizedFolder + "/";
    if (normalizedPath.startsWith(folderPath) || normalizedPath.startsWith(normalizedFolder)) {
      return true;
    }
  }
  const fileName = normalizedPath.split("/").pop() || "";
  for (const pattern of settings.excludedPatterns) {
    if (matchesPattern(normalizedPath, pattern) || matchesPattern(fileName, pattern)) {
      return true;
    }
  }
  return false;
}
function filterExcludedNotes(notes, settings) {
  const filtered = {};
  for (const [path, stats] of Object.entries(notes)) {
    if (!shouldExclude(path, settings)) {
      filtered[path] = stats;
    }
  }
  return filtered;
}

// src/tracker.ts
var ReadingTimeTracker = class {
  constructor(app, statsManager, settings, saveDataCallback, updateCallback = () => {
  }) {
    this.currentFile = null;
    this.sessionStartTime = null;
    this.accumulatedTime = 0;
    this.hasEdited = false;
    this.trackingIntervalId = null;
    this.updateIntervalId = null;
    this.onFileChange = null;
    this.onEditorChange = null;
    this.app = app;
    this.statsManager = statsManager;
    this.settings = settings;
    this.saveDataCallback = saveDataCallback;
    this.updateCallback = updateCallback;
  }
  /**
   * Start tracking
   */
  start() {
    this.onFileChange = this.app.workspace.on("active-leaf-change", () => {
      this.handleFileChange();
    });
    this.onEditorChange = this.app.workspace.on("editor-change", () => {
      this.hasEdited = true;
    });
    this.handleFileChange();
    this.startPeriodicSave();
    this.startPeriodicUpdate();
  }
  /**
   * Stop tracking
   */
  stop() {
    this.saveCurrentSession();
    this.stopTracking();
    if (this.onFileChange) {
      this.app.workspace.offref(this.onFileChange);
    }
    if (this.onEditorChange) {
      this.app.workspace.offref(this.onEditorChange);
    }
    if (this.trackingIntervalId) {
      window.clearInterval(this.trackingIntervalId);
    }
    if (this.updateIntervalId) {
      window.clearInterval(this.updateIntervalId);
    }
  }
  /**
   * Update settings
   */
  updateSettings(settings) {
    this.settings = settings;
  }
  /**
   * Notify the tracker that a tracked file has been deleted.
   * Discards any in-flight session so its data is not saved against the
   * (now removed) path.
   */
  handleFileDeleted(path) {
    var _a;
    if (((_a = this.currentFile) == null ? void 0 : _a.path) === path) {
      this.stopTracking();
    }
  }
  /**
   * Notify the tracker that a tracked file has been renamed/moved.
   * Persists any pending session under the new path so reading time is
   * not lost.
   */
  handleFileRenamed(oldPath, newFile) {
    var _a;
    if (((_a = this.currentFile) == null ? void 0 : _a.path) === oldPath) {
      this.currentFile = newFile;
    }
  }
  /**
   * Get current tracking status for display
   */
  getStatus() {
    var _a, _b;
    const currentSessionTime = this.sessionStartTime !== null ? Math.floor((Date.now() - this.sessionStartTime) / 1e3) + this.accumulatedTime : 0;
    const existingStats = this.currentFile ? this.statsManager.getNoteStats(this.currentFile.path) : null;
    const totalTime = existingStats ? existingStats.totalReadingTime + currentSessionTime : currentSessionTime;
    return {
      filePath: (_b = (_a = this.currentFile) == null ? void 0 : _a.path) != null ? _b : null,
      currentSessionTime,
      totalTime,
      hasEdited: this.hasEdited
    };
  }
  /**
   * Handle file change event
   */
  handleFileChange() {
    var _a;
    const activeFile = this.app.workspace.getActiveFile();
    if ((activeFile == null ? void 0 : activeFile.path) === ((_a = this.currentFile) == null ? void 0 : _a.path)) {
      return;
    }
    this.saveCurrentSession();
    this.updateCallback();
    if (activeFile && activeFile.extension === "md") {
      if (shouldExclude(activeFile.path, this.settings)) {
        this.stopTracking();
      } else {
        this.startTracking(activeFile);
      }
    } else {
      this.stopTracking();
    }
  }
  /**
   * Start tracking a file
   */
  startTracking(file) {
    this.currentFile = file;
    this.sessionStartTime = Date.now();
    this.accumulatedTime = 0;
    this.hasEdited = false;
  }
  /**
   * Stop tracking
   */
  stopTracking() {
    this.currentFile = null;
    this.sessionStartTime = null;
    this.accumulatedTime = 0;
    this.hasEdited = false;
  }
  /**
   * Save current reading session
   */
  saveCurrentSession() {
    if (!this.currentFile || this.sessionStartTime === null) {
      return;
    }
    const duration = Math.floor((Date.now() - this.sessionStartTime) / 1e3) + this.accumulatedTime;
    if (duration >= this.settings.minSessionTime) {
      this.statsManager.recordReading(
        this.currentFile.path,
        duration,
        this.hasEdited
      );
    }
    this.sessionStartTime = Date.now();
    this.accumulatedTime = 0;
    this.hasEdited = false;
  }
  /**
   * Start periodic save to persist data
   */
  startPeriodicSave() {
    this.trackingIntervalId = window.setInterval(() => {
      this.saveCurrentSession();
      void this.saveDataCallback();
    }, 3e4);
  }
  /**
   * Start periodic UI update
   */
  startPeriodicUpdate() {
    this.updateIntervalId = window.setInterval(() => {
      this.updateCallback();
    }, 2e3);
  }
};

// src/popularity.ts
function daysBetween(date1, date2) {
  const msPerDay = 1e3 * 60 * 60 * 24;
  const diffTime = Math.abs(date2.getTime() - date1.getTime());
  return Math.floor(diffTime / msPerDay);
}
function getTimeRangeStart(range) {
  const now = /* @__PURE__ */ new Date();
  switch (range) {
    case "today":
      return new Date(now.getFullYear(), now.getMonth(), now.getDate());
    case "week":
      return new Date(now.getTime() - 7 * 24 * 60 * 60 * 1e3);
    case "month":
      return new Date(now.getTime() - 30 * 24 * 60 * 60 * 1e3);
    case "quarter":
      return new Date(now.getTime() - 90 * 24 * 60 * 60 * 1e3);
    case "year":
      return new Date(now.getFullYear() - 1, now.getMonth(), now.getDate());
    case "all":
      return /* @__PURE__ */ new Date(0);
    default:
      return /* @__PURE__ */ new Date(0);
  }
}
function isWithinTimeRange(stats, rangeStart) {
  const lastRead = new Date(stats.lastReadAt);
  return lastRead >= rangeStart;
}
function calculatePopularity(stats, settings) {
  const now = /* @__PURE__ */ new Date();
  const lastRead = new Date(stats.lastReadAt);
  const daysSinceLastRead = daysBetween(now, lastRead);
  const score = stats.totalReadingTime / 60 * settings.readingTimeWeight + stats.readingCount * settings.readingCountWeight - daysSinceLastRead * settings.recencyDecayFactor;
  return Math.max(0, score);
}
function getPopularNotes(notes, settings, limit = settings.popularNotesLimit, timeRange = "all") {
  const now = /* @__PURE__ */ new Date();
  const rangeStart = getTimeRangeStart(timeRange);
  const filteredNotes = filterExcludedNotes(notes, settings);
  const popularNotes = Object.entries(filteredNotes).filter(([_, stats]) => isWithinTimeRange(stats, rangeStart)).map(([path, stats]) => {
    var _a;
    const lastRead = new Date(stats.lastReadAt);
    const daysSinceLastRead = daysBetween(now, lastRead);
    const name = ((_a = path.split("/").pop()) == null ? void 0 : _a.replace(/\.md$/, "")) || path;
    return {
      path,
      name,
      score: calculatePopularity(stats, settings),
      stats,
      daysSinceLastRead
    };
  });
  return popularNotes.sort((a, b) => b.score - a.score).slice(0, limit);
}
function formatReadingTime(seconds) {
  if (seconds < 60) {
    return `${seconds}s`;
  }
  const minutes = Math.floor(seconds / 60);
  const remainingSeconds = seconds % 60;
  if (minutes < 60) {
    return remainingSeconds > 0 ? `${minutes}m ${remainingSeconds}s` : `${minutes}m`;
  }
  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  return remainingMinutes > 0 ? `${hours}h ${remainingMinutes}m` : `${hours}h`;
}
function formatLastVisited(lastReadAt) {
  const lastRead = new Date(lastReadAt);
  const now = /* @__PURE__ */ new Date();
  const diffMs = now.getTime() - lastRead.getTime();
  const diffDays = Math.floor(diffMs / (1e3 * 60 * 60 * 24));
  const diffHours = Math.floor(diffMs / (1e3 * 60 * 60));
  const diffMinutes = Math.floor(diffMs / (1e3 * 60));
  if (diffMinutes < 1) {
    return "Just now";
  }
  if (diffMinutes < 60) {
    return `${diffMinutes}m ago`;
  }
  if (diffHours < 24) {
    return `${diffHours}h ago`;
  }
  if (diffDays === 1) {
    return "Yesterday";
  }
  if (diffDays < 7) {
    return `${diffDays} days ago`;
  }
  return lastRead.toLocaleDateString();
}

// src/main.ts
var VIEW_TYPE = "reading-time-stat-view";
var ReadingTimeStatPlugin = class extends import_obsidian.Plugin {
  async onload() {
    const savedData = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, savedData == null ? void 0 : savedData.settings);
    const statsData = savedData == null ? void 0 : savedData.stats;
    this.statsManager = new StatsManager(statsData, this.settings);
    this.tracker = new ReadingTimeTracker(
      this.app,
      this.statsManager,
      this.settings,
      this.saveStats.bind(this),
      () => {
        const view = this.getView();
        if (view) {
          view.update();
        }
      }
    );
    this.registerView(VIEW_TYPE, (leaf) => new ReadingTimeStatView(leaf, this));
    this.addRibbonIcon("rose", "Reading time stats", () => {
      void this.activateView();
    });
    this.addCommand({
      id: "open-stats-view",
      name: "Open statistics view",
      callback: () => this.activateView()
    });
    this.addCommand({
      id: "show-popular-notes",
      name: "Show popular notes",
      callback: () => this.showPopularNotesModal()
    });
    this.addCommand({
      id: "export-stats",
      name: "Export statistics",
      callback: () => this.exportStats()
    });
    this.addCommand({
      id: "clear-stats",
      name: "Clear all statistics",
      callback: () => this.confirmClearStats()
    });
    this.addCommand({
      id: "clean-orphan-stats",
      name: "Clean orphan data",
      callback: () => this.cleanOrphanStats()
    });
    this.addSettingTab(new ReadingTimeStatSettingTab(this.app, this));
    this.tracker.start();
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        var _a;
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.tracker.handleFileDeleted(file.path);
          if (this.statsManager.deleteNote(file.path)) {
            void this.saveStats();
            (_a = this.getView()) == null ? void 0 : _a.update();
          }
        }
      })
    );
    this.registerEvent(
      this.app.vault.on("rename", (file, oldPath) => {
        var _a;
        if (file instanceof import_obsidian.TFile && file.extension === "md") {
          this.tracker.handleFileRenamed(oldPath, file);
          if (this.statsManager.migrateNote(oldPath, file.path)) {
            void this.saveStats();
            (_a = this.getView()) == null ? void 0 : _a.update();
          }
        }
      })
    );
    this.register(() => this.tracker.stop());
  }
  onunload() {
    this.tracker.stop();
    void this.saveStats();
  }
  /**
   * Save stats data to disk
   */
  async saveStats() {
    await this.saveData({
      settings: this.settings,
      stats: this.statsManager.getData()
    });
  }
  /**
   * Save settings only
   */
  async saveSettings() {
    await this.saveStats();
  }
  /**
   * Activate the stats view
   */
  async activateView() {
    const { workspace } = this.app;
    let leaf = null;
    const leaves = workspace.getLeavesOfType(VIEW_TYPE);
    if (leaves.length > 0) {
      leaf = leaves[0];
    } else {
      leaf = workspace.getRightLeaf(false);
      if (leaf) {
        await leaf.setViewState({ type: VIEW_TYPE, active: true });
      }
    }
    if (leaf) {
      void workspace.revealLeaf(leaf);
    }
  }
  /**
  * Show popular notes in a modal
      */
  showPopularNotesModal(timeRange = "all") {
    const popularNotes = getPopularNotes(
      this.statsManager.getAllNotes(),
      this.settings,
      this.settings.popularNotesLimit,
      timeRange
    );
    new PopularNotesModal(this.app, this, popularNotes, this.settings, this.statsManager, timeRange).open();
  }
  /**
   * Export statistics as JSON
   */
  async exportStats() {
    const data = {
      exportedAt: (/* @__PURE__ */ new Date()).toISOString(),
      settings: this.settings,
      stats: this.statsManager.getData(),
      summary: this.statsManager.getSummary()
    };
    const fileName = `reading-stats-${(/* @__PURE__ */ new Date()).toISOString().split("T")[0]}.json`;
    const filePath = `${this.app.vault.configDir}/plugins/reading-time-stat/${fileName}`;
    await this.app.vault.adapter.write(filePath, JSON.stringify(data, null, 2));
    new import_obsidian.Notice(`Stats exported to ${fileName}`);
  }
  /**
   * Confirm and clear all statistics
   */
  confirmClearStats() {
    new ConfirmModal(
      this.app,
      "Clear all statistics",
      "This will permanently delete all reading time statistics. Are you sure?",
      async () => {
        this.statsManager.clearAll();
        await this.saveStats();
        const view = this.getView();
        if (view) {
          view.update();
        }
        new import_obsidian.Notice("All statistics cleared");
      }
    ).open();
  }
  /**
   * Remove stats for files that no longer exist in the vault
   */
  async cleanOrphanStats() {
    var _a;
    const existingPaths = new Set(
      this.app.vault.getMarkdownFiles().map((f) => f.path)
    );
    const removed = this.statsManager.removeOrphans(existingPaths);
    if (removed > 0) {
      await this.saveStats();
      (_a = this.getView()) == null ? void 0 : _a.update();
      new import_obsidian.Notice(`Removed stats for ${removed} missing note${removed === 1 ? "" : "s"}`);
    } else {
      new import_obsidian.Notice("No orphan stats found");
    }
  }
  /**
   * Open a note by path, verifying it exists in the vault.
   * Returns true if the file was opened.
   */
  openNoteIfExists(path) {
    var _a;
    const file = this.app.vault.getAbstractFileByPath(path);
    if (file instanceof import_obsidian.TFile) {
      void this.app.workspace.openLinkText(path, "", true);
      return true;
    }
    new import_obsidian.Notice("Note no longer exists");
    if (this.statsManager.deleteNote(path)) {
      void this.saveStats();
      (_a = this.getView()) == null ? void 0 : _a.update();
    }
    return false;
  }
  /**
   * Get stats manager for view access
   */
  getStatsManager() {
    return this.statsManager;
  }
  /**
   * Get settings for view access
   */
  getSettings() {
    return this.settings;
  }
  /**
   * Get tracker for real-time status
   */
  getTracker() {
    return this.tracker;
  }
  /**
   * Get the view instance if it exists
   */
  getView() {
    const leaves = this.app.workspace.getLeavesOfType(VIEW_TYPE);
    if (leaves.length > 0 && leaves[0].view instanceof ReadingTimeStatView) {
      return leaves[0].view;
    }
    return null;
  }
};
var ReadingTimeStatView = class extends import_obsidian.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.currentTimeRange = "all";
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE;
  }
  getDisplayText() {
    return "Reading time stats";
  }
  getIcon() {
    return "rose";
  }
  onOpen() {
    this.update();
    return Promise.resolve();
  }
  onClose() {
    return Promise.resolve();
  }
  destroy() {
  }
  /**
   * Update the view content
   */
  update() {
    var _a, _b;
    const container = this.containerEl.children[1];
    container.empty();
    container.addClass("reading-time-stat-container");
    const summary = this.plugin.getStatsManager().getSummary();
    const summaryDiv = container.createDiv({ cls: "stats-summary" });
    summaryDiv.createEl("h3", { text: "Overview" });
    summaryDiv.createEl("p", {
      text: `Tracking ${summary.totalNotes} notes`
    });
    summaryDiv.createEl("p", {
      text: `Total time: ${formatReadingTime(summary.totalTimeSeconds)}`
    });
    summaryDiv.createEl("p", {
      text: `${summary.totalSessions} reading sessions`
    });
    const filterDiv = container.createDiv({ cls: "time-range-filter" });
    filterDiv.createEl("span", { text: "Time range: ", cls: "filter-label" });
    const select = filterDiv.createEl("select", { cls: "time-range-select" });
    for (const option of TIME_RANGE_OPTIONS) {
      const optEl = select.createEl("option", {
        value: option.value,
        text: option.label
      });
      if (option.value === this.currentTimeRange) {
        optEl.selected = true;
      }
    }
    select.addEventListener("change", (e) => {
      const target = e.target;
      this.currentTimeRange = target.value;
      this.update();
    });
    const allPopularNotes = getPopularNotes(
      this.plugin.getStatsManager().getAllNotes(),
      this.plugin.getSettings(),
      this.plugin.getSettings().popularNotesLimit,
      this.currentTimeRange
    );
    const popularNotes = allPopularNotes.filter(
      (note) => this.app.vault.getAbstractFileByPath(note.path) !== null
    );
    const popularDiv = container.createDiv({ cls: "popular-notes" });
    const rangeLabel = ((_a = TIME_RANGE_OPTIONS.find((o) => o.value === this.currentTimeRange)) == null ? void 0 : _a.label) || "All Time";
    popularDiv.createEl("h3", { text: "Popular notes" });
    popularDiv.createEl("span", {
      text: rangeLabel,
      cls: "time-range-badge"
    });
    if (popularNotes.length === 0) {
      popularDiv.createEl("p", {
        text: "No statistics for this time range.",
        cls: "no-stats"
      });
    } else {
      const list = popularDiv.createEl("ul", { cls: "popular-list" });
      for (let i = 0; i < popularNotes.length; i++) {
        const note = popularNotes[i];
        const item = list.createEl("li", { cls: "popular-item" });
        const rankBadge = item.createEl("span", { cls: "rank-badge" });
        rankBadge.textContent = `#${i + 1}`;
        if (i === 0)
          rankBadge.addClass("rank-first");
        item.createEl("a", {
          text: note.name,
          cls: "note-name"
        }).addEventListener("click", () => {
          this.plugin.openNoteIfExists(note.path);
        });
        const statsRow = item.createDiv({ cls: "stats-row" });
        statsRow.createEl("span", {
          text: formatReadingTime(note.stats.totalReadingTime),
          cls: "stat-item stat-time"
        });
        statsRow.createEl("span", {
          text: `${note.stats.readingCount}`,
          cls: "stat-item stat-count"
        });
        statsRow.createEl("span", {
          text: formatLastVisited(note.stats.lastReadAt),
          cls: "stat-item stat-date"
        });
      }
    }
    const trackingStatus = this.plugin.getTracker().getStatus();
    const trackingDiv = container.createDiv({ cls: "current-note-stats" });
    trackingDiv.createEl("h3", { text: "Currently tracking" });
    if (trackingStatus.filePath) {
      const fileName = ((_b = trackingStatus.filePath.split("/").pop()) == null ? void 0 : _b.replace(/\.md$/, "")) || trackingStatus.filePath;
      trackingDiv.createEl("p", {
        text: fileName,
        cls: "current-file-name"
      });
      const statsGrid = trackingDiv.createDiv({ cls: "tracking-stats-grid" });
      const sessionDiv = statsGrid.createDiv({ cls: "stat-box" });
      sessionDiv.createEl("span", { text: "Session", cls: "stat-label" });
      sessionDiv.createEl("span", {
        text: formatReadingTime(trackingStatus.currentSessionTime),
        cls: "stat-value live"
      });
      const totalDiv = statsGrid.createDiv({ cls: "stat-box" });
      totalDiv.createEl("span", { text: "Total", cls: "stat-label" });
      totalDiv.createEl("span", {
        text: formatReadingTime(trackingStatus.totalTime),
        cls: "stat-value"
      });
      const existingStats = this.plugin.getStatsManager().getNoteStats(trackingStatus.filePath);
      if (existingStats) {
        const sessionsDiv = statsGrid.createDiv({ cls: "stat-box" });
        sessionsDiv.createEl("span", { text: "Sessions", cls: "stat-label" });
        sessionsDiv.createEl("span", {
          text: String(existingStats.readingCount + 1),
          cls: "stat-value"
        });
        trackingDiv.createEl("p", {
          text: `First read: ${new Date(existingStats.firstReadAt).toLocaleDateString()}`,
          cls: "first-read-date"
        });
      } else {
        trackingDiv.createEl("p", {
          text: "First time reading this note",
          cls: "first-time"
        });
      }
    } else {
      trackingDiv.createEl("p", {
        text: "No Markdown file active or excluded",
        cls: "no-tracking"
      });
    }
  }
};
var PopularNotesModal = class extends import_obsidian.Modal {
  constructor(app, plugin, notes, settings, statsManager, timeRange = "all") {
    super(app);
    this.tableContainer = null;
    this.plugin = plugin;
    this.notes = notes;
    this.settings = settings;
    this.statsManager = statsManager;
    this.currentTimeRange = timeRange;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.addClass("popular-notes-modal");
    contentEl.createEl("h2", { text: "Popular notes ranking" });
    const filterDiv = contentEl.createDiv({ cls: "modal-filter" });
    filterDiv.createEl("span", { text: "Time range: ", cls: "filter-label" });
    const select = filterDiv.createEl("select", { cls: "time-range-select" });
    for (const option of TIME_RANGE_OPTIONS) {
      const optEl = select.createEl("option", {
        value: option.value,
        text: option.label
      });
      if (option.value === this.currentTimeRange) {
        optEl.selected = true;
      }
    }
    select.addEventListener("change", (e) => {
      const target = e.target;
      this.currentTimeRange = target.value;
      this.updateNotes();
    });
    this.tableContainer = contentEl.createDiv({ cls: "table-container" });
    this.updateNotes();
  }
  /**
   * Update notes when time range changes
   */
  updateNotes() {
    const all = getPopularNotes(
      this.statsManager.getAllNotes(),
      this.settings,
      this.settings.popularNotesLimit,
      this.currentTimeRange
    );
    this.notes = all.filter(
      (note) => this.app.vault.getAbstractFileByPath(note.path) !== null
    );
    if (this.tableContainer) {
      this.tableContainer.empty();
      this.renderTable();
    }
  }
  /**
   * Render the notes table
   */
  renderTable() {
    if (!this.tableContainer)
      return;
    if (this.notes.length === 0) {
      this.tableContainer.createEl("p", { text: "No statistics for this time range.", cls: "no-stats" });
      return;
    }
    const table = this.tableContainer.createEl("table", { cls: "popular-table" });
    const thead = table.createEl("thead");
    const header = thead.createEl("tr");
    header.createEl("th", { text: "Rank" });
    header.createEl("th", { text: "Note" });
    header.createEl("th", { text: "Time" });
    header.createEl("th", { text: "Sessions" });
    header.createEl("th", { text: "Last visited" });
    header.createEl("th", { text: "Score" });
    const tbody = table.createEl("tbody");
    for (let i = 0; i < this.notes.length; i++) {
      const note = this.notes[i];
      const row = tbody.createEl("tr");
      if (i === 0)
        row.addClass("top-note");
      const rankCell = row.createEl("td");
      const rankBadge = rankCell.createEl("span", { cls: "modal-rank-badge" });
      rankBadge.textContent = `#${i + 1}`;
      if (i < 3)
        rankBadge.addClass(`rank-${i + 1}`);
      const noteCell = row.createEl("td");
      noteCell.createEl("a", { text: note.name }).addEventListener("click", () => {
        if (this.plugin.openNoteIfExists(note.path)) {
          this.close();
        } else {
          this.updateNotes();
        }
      });
      row.createEl("td").createEl("span", {
        text: formatReadingTime(note.stats.totalReadingTime),
        cls: "modal-stat"
      });
      row.createEl("td").createEl("span", {
        text: `${note.stats.readingCount}`,
        cls: "modal-stat"
      });
      row.createEl("td", { text: formatLastVisited(note.stats.lastReadAt) });
      row.createEl("td").createEl("span", {
        text: `${Math.round(note.score)}`,
        cls: "modal-score"
      });
    }
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ConfirmModal = class extends import_obsidian.Modal {
  constructor(app, title, message, onConfirm) {
    super(app);
    this.title = title;
    this.message = message;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: this.title });
    contentEl.createEl("p", { text: this.message });
    const buttons = contentEl.createDiv({ cls: "modal-buttons" });
    buttons.createEl("button", { text: "Cancel" }).addEventListener("click", () => this.close());
    buttons.createEl("button", { text: "Confirm", cls: "mod-warning" }).addEventListener("click", () => {
      void this.onConfirm();
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var ReadingTimeStatSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setName("Configuration").setHeading();
    new import_obsidian.Setting(containerEl).setName("Reading time weight").setDesc("Weight for reading time in popularity calculation (per minute)").addSlider(
      (slider) => slider.setLimits(0.1, 5, 0.1).setValue(this.plugin.getSettings().readingTimeWeight).setDynamicTooltip().onChange((value) => {
        this.plugin.getSettings().readingTimeWeight = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Reading count weight").setDesc("Weight for reading count in popularity calculation").addSlider(
      (slider) => slider.setLimits(1, 20, 1).setValue(this.plugin.getSettings().readingCountWeight).setDynamicTooltip().onChange((value) => {
        this.plugin.getSettings().readingCountWeight = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Recency decay factor").setDesc("How much popularity decays per day since last read").addSlider(
      (slider) => slider.setLimits(0, 0.5, 0.01).setValue(this.plugin.getSettings().recencyDecayFactor).setDynamicTooltip().onChange((value) => {
        this.plugin.getSettings().recencyDecayFactor = value;
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Popular notes limit").setDesc("Maximum number of popular notes to display").addText(
      (text) => text.setValue(String(this.plugin.getSettings().popularNotesLimit)).onChange((value) => {
        var _a;
        const num = parseInt(value);
        if (num > 0) {
          this.plugin.getSettings().popularNotesLimit = num;
          void this.plugin.saveSettings();
          (_a = this.plugin.getView()) == null ? void 0 : _a.update();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Minimum session time").setDesc("Minimum seconds to count as a reading session").addText(
      (text) => text.setValue(String(this.plugin.getSettings().minSessionTime)).onChange((value) => {
        const num = parseInt(value);
        if (num >= 0) {
          this.plugin.getSettings().minSessionTime = num;
          void this.plugin.saveSettings();
        }
      })
    );
    new import_obsidian.Setting(containerEl).setName("Exclusions").setHeading();
    containerEl.createEl("p", {
      text: "Exclude certain folders or files from tracking (e.g., kanban boards, templates, todo lists)",
      cls: "settings-section-desc"
    });
    new import_obsidian.Setting(containerEl).setName("Excluded folders").setDesc("Folder paths to exclude, one per line. Example: kanban/, templates/").addTextArea(
      (text) => text.setPlaceholder("kanban/\ntemplates/\narchive/").setValue(this.plugin.getSettings().excludedFolders.join("\n")).onChange((value) => {
        this.plugin.getSettings().excludedFolders = value.split("\n").map((s) => s.trim()).filter((s) => s.length > 0);
        void this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("Excluded file patterns").setDesc("File name patterns to exclude, supports * wildcard. One per line. Example: todo-*, *-kanban").addTextArea(
      (text) => text.setPlaceholder("todo-*\n*-kanban\ndaily note*").setValue(this.plugin.getSettings().excludedPatterns.join("\n")).onChange((value) => {
        this.plugin.getSettings().excludedPatterns = value.split("\n").map((s) => s.trim()).filter((s) => s.length > 0);
        void this.plugin.saveSettings();
      })
    );
  }
};
